eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8100
spring:
  application:
    name: cloud-ticketfront
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#  thymeleaf:
#    mode: LEGACYHTML5
#    cache: false


