eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8100
spring:
  application:
    name: cloud-ticketfront
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

feign:
  hystrix:
    enabled: true
#  thymeleaf:
#    mode: LEGACYHTML5
#    cache: false


