eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8300
spring:
  application:
    name: cloud-ticketserver
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/db_haocaicloud?serverTimezone=UTC
    username: root
    password: 123456