eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8400
spring:
  application:
    name: cloud-orderserver
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/db_haocaicloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    druid:
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      filters: stat,config
  jackson:
    #指定日期格式化时区
    time-zone: GMT+8

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.haocai.ticketserver.cloudticketserver.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #id-type: 1
    #key-generator: com.baomidou.mybatisplus.incrementer.PostgreKeyGenerator
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    #field-strategy: 2
    #驼峰下划线转换
    #db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level:
    com.sinoprof: DEBUG
    jdbc.sqltiming: DEBUG