eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8800
spring:
  application:
    name: cloud-mybatisgenerator
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/db_haocaicloud??useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    druid:
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      filters: stat,config
mybatis:
  mapper-location=classpath: sql/*.xml